baseURL = 'https://retr0sity.github.io/'
languageCode = 'en-us'
title = 'Ioannis Karkalas'
theme = 'PaperMod'

[params]
  description = "This webpage represents my projects, skills and my newfound passion for game development"
  author = "Welcome to my portfolio! My name is Ioannis."
  
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/retr0sity"
  
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/ioannis-karkalas"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2