baseURL = 'https://retr0sity.github.io/'
languageCode = 'en-us'
title = 'Ioannis Karkalas'
theme = 'PaperMod'

[params]
  description = "This webpage illustrates my projects, skills and my newfound passion for game development"
  author = "Ioannis Karkalas"
  ShowShareButtons = false
  ShowReadingTime = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  
  [params.profileMode]
    enabled = true
    title = "Hey there! Welcome to my website! ðŸ‘‹"
    subtitle = "This page illustrates my projects, skills and newfound passion for game development."
    imageUrl = "/profile.png"
    imageWidth = 400
    imageHeight = 400
    imageTitle = "my profile picture"
  
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/retr0sity"
  
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/ioannis-karkalas"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2